export const MARK_AS_READ = 'MARK_AS_READ';
export const MARK_AS_ARCHIVE = 'MARK_AS_ARCHIVE';
export const MARK_AS_UNARCHIVE = 'MARK_AS_UNARCHIVE';
export const MARK_SOME_AS_READ = 'MARK_SOME_AS_READ';
export const MARK_SOME_AS_ARCHIVE = 'MARK_SOME_AS_ARCHIVE';